name: Generate Google Play Keystore
on:
  workflow_dispatch: # Manuel tetiklemek için

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create Keystore
        run: |
          keytool -genkey -v -keystore koschei.keystore \
          -alias koschei_alias -keyalg RSA -keysize 2048 \
          -validity 10000 \
          -storepass Koschei123! -keypass Koschei123! \
          -dname "CN=Koschei, OU=Dev, O=KoscheiAI, L=Istanbul, S=Istanbul, C=TR"
      
      - name: Upload Keystore as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: google-play-keystore
          path: koschei.keystore
